config/routes.rb
 =Splu::Application.routes.draw do

  root 'quotes#index'

  resources :quotes

  get 'about', to: 'quotes#about'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end
  
  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Splu</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="col-xs-2">
      <%= link_to root_path, class: 'logo' do %>
      <div class="circle">
        <br />
        KEEP
        <br />
        ON
        <br />
        SWIMMING
      </div>
    <% end %>
    </div>
    <div class="col-sm-4 hidden-xs slogan">
      When life hands you lemons...
    </div>
    <div class="col-xs-8 col-xs-offset-2 col-sm-offset-1 col-sm-5 links">
    <!-- Button trigger modal -->
    <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to'About', about_path %>
    </div>
  </header>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
        </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
            <%= f.input :saying, label: "What saying would you like to add?", placeholder: "I woke up like this!" %>
            <br />
            <%= f.input :author, label: "Who is the author of this quote?", placeholder: "Beyonce" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <hr />

  <br class="clear" />

  <div class="container">
    <% if flash[:error].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
    <%= yield %>
  </div>

<div class="footer">
  <div class="container">
    <div class="col-xs-12 col-sm-6">
      <%= link_to "Click for more quotes!", root_path, class: 'next-quote' %>
    </div>
    <div class="col-xs-12 col-sm-6 footer-blurb">
      Built by Charlie O'Hara
    </div>
  </div>
</div>
</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About Splurty</h1>
  <br />
  <p>
    Splurty was built by Charlie O'Hara, a code newbie excited to be part of the Firehose Project.
  </p>
  <p>
    Want to build your own Splurty?  Check out the <a class="about" target="_blank" href="http://www.thefirehoseproject.com/">Firehose Project.</a>
  </p>
  <br />
  <br />

  <div class="col-xs-12 col-sm-4">
    <%= image_tag 'charlie.jpg', class: 'img-responsive' %>
  </div>

  <div class="col-xs-12 col-sm-7 col-sm-offset-1">
    <h2 class="text-center">Charlie O'Hara</h2>
    <br />
    <p>
      Charlie O'Hara is excited to be sinking his teeth into computer programming.  Charlie earned his bachelor's degree in biology from UC Santa Barbara but did not feel driven to pursue a career in that field.  He had been taking community college classes exploring fields as diverse as engineering and psychology when his friend suggested he take a computer programming course.   
    </p>
    <br />
    <p>
      Charlie is excited to finally have found a career that he feels passionate to pursue.  There is a lot of satisfaction in solving the small puzzles that make up an application like Splurty.   Even after hours of struggle, Charlie finds so much satisfaction in being able to punch his fist in the air at the end of a coding victory.
    </p>
    <br />
    <p>
    If you want to see what Charlie is working on, check out his <a class="about"target="_blank" href="https://github.com/cbohara?tab=repositories">github</a> account!
  </p>
  </div>
  <br class="clear" />
</div>

<br class="clear" />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
  <span>Quote No. <%= @quote.id %></span>
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/new.html.erb
<h1>Enter Your Quote Details</h1>
<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>